

en_experience_list = [
    "1+ year working with",
    "4+ years of hands-on experience",
    "year of experience",
    "years of experience",
    "years experience",
    "yrs of experience",
    "of experience",
    "professional experience",
    "commercial experience",
    "at least",
    "minimum experience",
    "required experience",
    "hands-on experience",
    "1+ year experience",
    "2+ years experience",
    "3 years experience",
    "work experience",
    "years of hands-on experience",
    "+ years of professional",
    "+ years of experience in",
    "+ years of professional experience",
    "Commercial experience with Python",
]


ua_experience_list = [
    "рік досвіду",
    "роки досвіду",
    "років досвіду",
    "рік комерційного досвіду",
    "професійного досвіду",
    "досвід роботи",
    "досвід з",
    "досвід у",
    "мінімальний досвід",
    "щонайменше рік досвіду",
    "не менше ніж",
    "від одного року досвіду",
    "від двох років досвіду",
    "від 3 років досвіду"
]


ignore_experience_list = [
        "we are",
        "We’re",
        "with",
        "company with more",
        "team with over",
        "company with over",
        "more than years of experience",
        "we are a leading ",
        "роки ми успішно",
]

years_of_experience = en_experience_list + ua_experience_list

technologies_dict = {
    "python": ["python", "django", "flask", "fastapi", "ai", "machine learning", "pandas", "numpy", "aiogram","oop"],
    "git": ["git", "github", "gitlab", "version control system"],
    "postgresql": ["postgresql", "postgres", "sql", "orm", "sqlalchemy"],
    "mongodb": ["mongodb", "nosql", "document database"],
    "sqlite": ["sqlite"],
    "flask": ["flask"],
    "django": ["django", "django rest framework", "drf", "web framework"],
    "fastapi": ["fastapi", "async api", "pydantic"],
    "pandas": ["pandas"],
    "beautiful_soup": ["beautiful soup"],
    "docker": ["docker", "docker compose", "kubernetes", "containerization"],
    "sql": ["sql", "mysql"],
    "javascript": ["javascript", "js", "typescript"],
    "react": ["react", "react hooks", "frontend", "javascript framework"],
    "css": ["css"],
    "html": ["html"],
    "celery": ["celery", "task queue", "distributed tasks"],
    "redis": ["redis", "cache", "message broker"],
    "rabbitmq": ["rabbitmq", "message queue", "amqp"],
    "tensorflow": ["tensorflow", "deep learning", "neural networks"],
    "machine_learning": ["machine learning", "ml", "llm", "etl", "data science"],
    "scrum": ["scrum", "agile"],
    "unit_testing": ["unit-тестування", "unit testing", "pytest"],
    "aws": ["aws", "amazon web services", "cloud", "gcp", "azure"],
    "kubernetes": ["kubernetes"],
    "openai": ["openai"],
    "selenium": ["selenium", "web testing", "automation","playwright","2Captcha"],
    "vuejs": ["vue.js", "vue"],
    "php": ["php"],
    "laravel": ["laravel"],
    "nodejs": ["node.js", "nodejs"],
    "openapi": ["openapi", "swagger", "api documentation"],
    "json": ["json"],
    "rest_api": ["rest api", "rest"],
    "graphql": ["graphql", "api query language"],
    "powerbi": ["power bi", "ms power bi"],
    "vba": ["vba"],
    "sas": ["sas"],
    "dax": ["dax"],
    "ms365": ["microsoft 365", "ms365"],
    "jupyter": ["jupyter", "jupyter notebook"],
    "pytest": ["pytest", "testing", "unit image"],
    "grpc": ["grpc"],
    "kafka": ["kafka", "event streaming", "message broker"],
    "pytorch": ["pytorch", "machine learning", "deep learning"],
    "jenkins": ["jenkins", "gerrit", "ci/cd", "automation server"],
    "autonomous_systems": ["autonomous guidance", "autonomous navigation", "gnss", "gps", "imu", "sensor fusion"],
    "aerospace": ["aerospace", "avionics", "flight dynamics", "orbital mechanics"],
    "embedded": ["embedded systems", "rtos", "microcontrollers", "arm cortex"],
    "computer_vision": ["computer vision", "opencv", "slam", "visual odometry"],
    "robotics": ["robotics", "ros", "robot operating system", "motion planning"],
    "control_systems": ["control systems", "pid control", "kalman filter", "state estimation"],
    "c++": ["c++", "cpp", "modern c++", "c++17", "c++20"],
    "matlab": ["matlab", "simulink"],
    "linux": ["linux", "embedded linux", "yocto"],
    "dsp": ["digital signal processing", "dsp", "filters", "fft"],
    "simulation": ["simulation", "monte carlo", "mathematical modeling"],
    "testing": ["unit testing", "hardware testing", "system testing"],
    "communication_protocols": ["uart", "spi", "i2c", "can bus", "ethernet"],
    "ai_ml": ["artificial intelligence", "machine learning", "neural networks", "deep learning"],
    "sensors": ["lidar", "radar", "imu", "gyroscope", "accelerometer"],
    "devops": ["ci/cd", "jenkins", "docker", "kubernetes"],
    "security": ["cybersecurity", "encryption", "secure coding"]
}


soft_skills_dict = {
    "teamwork": ["робота в команді", "teamwork", "collaboration", "співпраця"],
    "responsibility": ["відповідальність", "responsibility", "accountability"],
    "communication": ["комунікабельність", "communication", "комунікація", "communication skills"],
    "organization": ["організованість", "organization"],
    "self_motivation": ["самостійність", "ініціативність", "self-motivation", "initiative", "proactivity", "активність"],
    "learning": ["бажання вчитися і розвиватися", "здатність до навчання", "learning", "eager to learn"],
    "adaptability": ["адаптивність", "adaptability", "flexibility", "гнучкість"],
    "creativity": ["креативність", "creativity", "творчий підхід", "innovation", "новаторство"],
    "honesty": ["чесність", "honesty"],
    "reliability": ["надійність", "reliability"],
    "attention_to_detail": ["уважність", "attention to detail", "увага до деталей", "detail-oriented"],
    "productivity": ["продуктивність", "productivity"],
    "business_analysis": ["бізнес-аналіз", "business analysis"],
    "problem_solving": ["самостійне прийняття рішень", "problem solving", "decision making", "вирішення проблем", "troubleshooting"],
    "communication_with_clients": ["робота з дітьми", "communication with clients", "client communication"],
    "teaching": ["викладання", "teaching", "education"],
    "punctuality": ["пунктуальність", "punctuality"],
    "active_life_position": ["активна життєва позиція", "active life position"],
    "time_management": ["time management", "тайм-менеджмент"],
    "leadership": ["лідерство", "leadership", "management", "керівництво"],
    "critical_thinking": ["критичне мислення", "critical thinking", "analytical skills", "аналітичні навички"],
    "emotional_intelligence": ["емоційний інтелект", "emotional intelligence", "eq", "еі"],
    "conflict_resolution": ["вирішення конфліктів", "conflict resolution", "mediation"],
    "negotiation": ["переговори", "negotiation", "bargaining"],
    "presentation_skills": ["навички презентації", "presentation skills", "public speaking"]
}

